//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NSInmobiliaria.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string TELEFONO { get; set; }
        public string CELULAR { get; set; }
        public string MAIL { get; set; }
        public string DIRECCION { get; set; }
        public string REFERIDO { get; set; }
    }
}
